base_config: ./base.yaml
task_cls: tasks.vocoder.wavenet.WaveNetTask

###########################################################
#                WaveRNN ARCHITECTURE SETTING             #
###########################################################
input_type: "raw"
quantize_channels: 65536
silence_threshold: 2
output_distribution: "Logistic"
log_scale_min: -16.0
out_channels: 30
layers: 24
stacks: 4
residual_channels: 128
gate_channels: 256
skip_out_channels: 128
dropout: 0.0
kernel_size: 3
cin_channels: 80
cin_pad: 2
voc_pad: 2
upsample_conditional_features: true
upsample_net: "ConvInUpsampleNetwork"
"upsample_params": {
  "upsample_scales": [
    4,
    4,
    4,
    4
  ],
  "cin_pad": 2
}
gin_channels: -1
n_speakers: 1
use_pitch_embed: false

###########
# train and eval
###########
max_samples: 10240
max_sentences: 8
max_valid_sentences: 1
max_updates: 1000000
lr: 0.001
clip_grad_norm: 4              # set to None if no gradient clipping needed
generator_scheduler_params:
  step_size: 200000      # Generator's scheduler step size.
  gamma: 0.5             # Generator's scheduler gamma.
  # At each step size, lr will be multiplied by this parameter.