base_config:
  - ./pwg.yaml
task_cls: tasks.vocoder.fregan.FreGanTask
resblock: "1"
adam_b1: 0.8
adam_b2: 0.99
upsample_rates: [ 8,4,2,2,2 ]
upsample_kernel_sizes: [ 16,8,4,4,4 ]
upsample_initial_channel: 512
resblock_kernel_sizes: [ 3,7,11 ]
resblock_dilation_sizes: [ [ 1,3,5,7 ], [ 1,3,5,7 ], [ 1,3,5,7 ] ]

lambda_mel: 45.0
max_samples: 8192
max_sentences: 20

aux_context_window: 0 # Context window size for auxiliary feature.
generator_optimizer_params:
  lr: 0.0002            # Generator's learning rate.
generator_scheduler_params:
  step_size: 600
  gamma: 0.999
discriminator_optimizer_params:
  lr: 0.0002            # Discriminator's learning rate.
discriminator_scheduler_params:
  step_size: 600
  gamma: 0.999
max_updates: 3000000

audio_sample_rate: 16000
fmin: 0  # Set this to 55 if your speaker is male! if female, 95 should help taking off noise. (To test depending on dataset. Pitch info: male~[65, 260], female~[100, 525])
fmax: 8000  # To be increased/reduced depending on data.
